/**
 * @fileoverview Type definitions for the Smart Context RAG system.
 * 
 * This module defines all types used by the Smart Context system:
 * - IntentType: Classification of user query intentions
 * - SmartContextQuery: Parsed query with entities
 * - ContextPayload: Data package sent to Copilot
 * 
 * @module smart-context/types
 */

/**
 * Classification of detected user intentions.
 * Used by the intent router to determine the appropriate execution strategy.
 */
export enum IntentType {
    /** Count items matching specific filters */
    COUNT_FILTERED = 'COUNT_FILTERED',
    /** Rank categories by highest count (e.g., "top 10") */
    TOP_N_RANKING = 'TOP_N_RANKING',
    /** Rank categories by lowest count (e.g., "least common") */
    BOTTOM_N_RANKING = 'BOTTOM_N_RANKING',
    /** Show percentage distribution across categories */
    DISTRIBUTION = 'DISTRIBUTION',
    /** Find items containing a specific term */
    TERM_SEARCH = 'TERM_SEARCH',
    /** Find items with a term but NOT in a specific category */
    TERM_EXCEPTION = 'TERM_EXCEPTION',
    /** Display complete hierarchy path for a category */
    HIERARCHY_LOOKUP = 'HIERARCHY_LOOKUP',
    /** Get sample items from a specific category */
    CATEGORY_LOOKUP = 'CATEGORY_LOOKUP',
    /** Find unclassified items or missing subcategories */
    GAP_ANALYSIS = 'GAP_ANALYSIS',
    /** Detect descriptions with abnormal characteristics */
    OUTLIER_DETECTION = 'OUTLIER_DETECTION',
    /** Calculate Pareto (80/20) distribution */
    PARETO_ANALYSIS = 'PARETO_ANALYSIS',
    /** Intent could not be determined */
    UNKNOWN = 'UNKNOWN'
}

/**
 * Represents a parsed user query with extracted entities.
 * Generated by the entity extractor and used by the execution engine.
 */
export interface SmartContextQuery {
    /** Detected intent type */
    intent: IntentType;
    /** Extracted entities from the query */
    entities: {
        /** Category name found in query (e.g., "Indiretos") */
        category?: string;
        /** Hierarchy level specified (N1, N2, N3, or N4) */
        level?: 'N1' | 'N2' | 'N3' | 'N4';
        /** Target level for hierarchical queries */
        targetLevel?: 'N1' | 'N2' | 'N3' | 'N4';
        /** Type of target for the query */
        targetType?: 'item' | 'category' | 'word';
        /** Numeric value for top-N or threshold queries */
        number?: number;
        /** Search term for text-based queries */
        term?: string;
        /** Threshold value for outlier detection */
        threshold?: number;
        /** Filter by classification status */
        status?: 'unique' | 'ambiguous' | 'unclassified' | 'all';
    };
    /** Original unmodified user query */
    originalQuery: string;
}

/**
 * Context payload sent to the Copilot with enriched data.
 * Contains all information needed for the AI to generate a response.
 */
export interface ContextPayload {
    /** Raw JSON data relevant to the query */
    data: any;
    /** Formatted text representation for the prompt */
    text: string;
    /** Specific instructions for this context type */
    instructions: string;
    /** Subset of items for inspection */
    relevantItems: any[];
    /** Structured metadata for potential UI widgets */
    meta?: any;
}

